trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: validate
  jobs:
  - job: SecurityScan
    displayName: 'Run tfsec'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        # Pull the tfsec Docker image
        docker pull aquasec/tfsec

        # Run tfsec using the Docker image on your Terraform code
        docker run --rm -v $(Build.SourcesDirectory):/tfsec aquasec/tfsec

        # Capture the exit code of the tfsec Docker container
        TFSEC_EXIT_CODE=$?

        # Check the exit code and exit accordingly
        if [ $TFSEC_EXIT_CODE -eq 0 ]; then
          echo "tfsec scan passed successfully."
        else
          echo "tfsec scan failed with violations."
        fi
        exit $TFSEC_EXIT_CODE
      displayName: 'Run tfsec'
